// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASUZDrCZvytb0w6LPAfIvCR8frbsYUdKw',
    appId: '1:597163300495:web:befb0dc6df7bbb2e9142fa',
    messagingSenderId: '597163300495',
    projectId: 'rlcesi-bb20d',
    authDomain: 'rlcesi-bb20d.firebaseapp.com',
    databaseURL: 'https://rlcesi-bb20d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rlcesi-bb20d.appspot.com',
    measurementId: 'G-D76HX3PE5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEWABbkoxeLTZ10aFlFB_EqHCQVYv9VJo',
    appId: '1:597163300495:android:5cff05866d870f2a9142fa',
    messagingSenderId: '597163300495',
    projectId: 'rlcesi-bb20d',
    databaseURL: 'https://rlcesi-bb20d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rlcesi-bb20d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfWICTsNx89zgSs6O85M9GjX86TbLH1bA',
    appId: '1:597163300495:ios:a3f7c607a0f39b6e9142fa',
    messagingSenderId: '597163300495',
    projectId: 'rlcesi-bb20d',
    databaseURL: 'https://rlcesi-bb20d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rlcesi-bb20d.appspot.com',
    iosClientId: '597163300495-hi8k1n2ajdpbm9isljs10ldgvvhddgdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.rlcesi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfWICTsNx89zgSs6O85M9GjX86TbLH1bA',
    appId: '1:597163300495:ios:a3f7c607a0f39b6e9142fa',
    messagingSenderId: '597163300495',
    projectId: 'rlcesi-bb20d',
    databaseURL: 'https://rlcesi-bb20d-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'rlcesi-bb20d.appspot.com',
    iosClientId: '597163300495-hi8k1n2ajdpbm9isljs10ldgvvhddgdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.rlcesi',
  );
}
